version: '3.1'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: flask-crud
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_PASSWORD: admin123
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
